### ISSUE TITLE
help: wallhaven api

### ISSUE THREAD

**Issue by ErKeLost** [gamerfunky78/Fresco-wallpapers#1]
hi Hello, I'm sorry to bother you. I'm also working on a project about wallhaven api recently and I want to ask you a question. How to debug https://wallhaven.cc/api/v1 locally. I encountered a lot of problems locally, but the get request in the browser works normally. Do you have any good solution?

**Comment by Brianali-codes** [comment]
Hi there. Have you Tried using a cors proxy service or refer to their documentation. At first I was also getting errors related with the cors proxy but I used a service called corsproxy.io and the issue was solved. If the issue still continues there is a tonne of the proxies on the Internet. Also are you using the live server extension it could also be a problem if u aren't using it and if you are getting an error on the console on chrome after launching just forward me the error. If the error is something else kindly forward the screenshot or error to my email plasticfoods427@gmail.com 👍

**Comment by Brianali-codes** [comment]
If theres any other problem feel free to ask ill try my best to help :)

**Comment by ErKeLost** [comment]
> Owner

Thank you very much for your help. I will try again. If I have any questions, I will come back to ask you. Thank you again for your reply.

**Comment by Brianali-codes** [comment]
You are welcome and If you wanna collaborate on any projects too you can ask me am also an amateur😊
